language: csharp
mono: none

matrix:
  include:
  - os: linux # Ubuntu 14.04
    dist: trusty
    sudo: required
    dotnet: 2.0.0
  - os: osx # OSX 10.12
    osx_image: xcode9
    before_install:
    - brew update
    - curl https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
    - chmod +x dotnet-install.sh
    - ./dotnet-install.sh --channel 2.0
    - export PATH=$PATH:~/.dotnet/
    - ulimit -n 1024
    - os_platform=darwin

# branches to build 
branches:
  only:
  - master

env:
  global:
  - log_prefix=[$TRAVIS_OS_NAME]
  - arch=x64
  - configuration=Release  
  - os_platform=linux

cache:
  directories:
  - Breeze.UI/node_modules
  
# Work around NuGet issue #2163
# https://github.com/NuGet/Home/issues/2163
# https://github.com/travis-ci/travis-ci/issues/7728

install:
- nvm install 6

before_script:
- if [ -z "$TRAVIS_TAG" ] ; then TRAVIS_TAG=cd-unstable; fi

script:
- chmod +x build.sh
- "./build.sh"

deploy:
  provider: releases
  api_key:
    secure: $secure_github_key # this key is set on the Travis build page 
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/deploy/*.zip"
  skip_cleanup: true
  overwrite: true
  prerelease: true
  on:
    branch: master
    tags: true