language: csharp
mono: none
dotnet: 1.0.4
matrix:
  include:
  - os: linux # Ubuntu 14.04
    dist: trusty
    sudo: required
    env: os_version=ubuntu14.04
  - os: osx # OSX 10.11
    osx_image: xcode7.3
    env: os_version=10.11
  - os: osx # OSX 10.12
    osx_image: xcode8.1
    env: os_version=10.12

# branches to build 
branches:
  only:
  - master

env:
  global:
  - log_prefix=[$TRAVIS_OS_NAME]
  - arch=x64
  - configuration=Release  
  - os_platform=linux
  - TRAVIS_TAG=cd-unstable
  
# Work around NuGet issue #2163
# https://github.com/NuGet/Home/issues/2163
# https://github.com/travis-ci/travis-ci/issues/7728

before_install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024 ; os_platform=darwin ; fi

install:
- nvm install 6
script:
- chmod +x build.sh
- "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: NOLMkLtCu/WCUHBXroBPJsGT0U0Lw5x0SwZvxvCmQfqzM0R4XQ0ZV3GPRLSHHBOLER8CSucgFJ4XAbNG7yiIA2TrNfmv38su2KuBPQwA5DBpOBzBxQa2cqJV+9lgF48r5J+C0kkyQ8VUwpwXVeTenfxw7pPBIMfpFblOXFGRWHExJHX5o9u972heO1i/s6mM0v8EdJ72JswklLLHqevAIHw4NZ7ZMmvisnbTWuOt4IuOLbw/eobbZF9xX+9ks6uOUmfUEQ51KKRsIOFuOGW/1zxBudv60JypiYgGLcG7jbUR8m06MPDmWv5TLd8rAWNbb/djEJjm1aRjN30rVi1NXIl4Ybg3GfGF/Pqc67j0hLMIQD5Mp8h62yopXIAroTpKhcmeRDlMoG6fbcwOtlP+F5osZT25yJH7+zDesv57pMJZkL+RpG7W3bHQIiT4lq8xD1490NFLpUWLoaIDMwTWFLlp+uVfmMa+snx1A1MDKw3BkJrt3ten3/BMVXIu3sLkI5xJFJJgri756CxDeyuuj7UkMzYNvzqDZnlI1Gv0rjXAfIdMR/jRGRIbBx0b4YQf3Nwx+EymzvrKLYX1qX3DfW6b8qn2gIa6r3jUEwLTY/4tc0U+IXjl0hJnY9Rv871oWnV2k7mqfFxnaKAqWn4gdsliKmPbShMrsNkh/p0RQKg=
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/deploy/*.zip"
  skip_cleanup: true
  overwrite: true
  prerelease: true
  on:
    branch: master
    tags: true